---
- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Ensure Logstash is started and enabled on boot.
  service: "name=logstash state=started enabled={{ logstash_enabled_on_boot }}"
  sudo: true
